### ISSUE TITLE
WebGLRenderingDebugger.Inspectorsのコード補完

### ISSUE THREAD

**Issue by zprodev** [drecom/webgl-rendering-debugger#2]
型定義上`WebGLRenderingDebugger.Inspectors`がobjectになっているため、DRAW_CALLSやPOLYGONが補完で出ない。
https://github.com/drecom/webgl-rendering-debugger/blob/master/lib/lib-ts/index.d.ts#L17

**Comment by dolow** [comment]
対応 PR です。
https://github.com/drecom/webgl-rendering-debugger/pull/3
